name: Build Project

on:
  workflow_call:
    outputs:
      pluginName:
        description: Project name detected by parsing build spec file
        value: ${{ jobs.check-event.outputs.pluginName }}
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-event:
    name: Check GitHub Event Data 🔎
    runs-on: ubuntu-24.04
    outputs:
      pluginName: ${{ steps.setup.outputs.pluginName }}
      commitHash: ${{ steps.setup.outputs.commitHash }}
    steps:
      - uses: actions/checkout@v4

      - name: Check Event Data ☑️
        id: setup
        run: |
          echo "commitHash=${GITHUB_SHA:0:9}" >> $GITHUB_OUTPUT
          
          plugin_name="$(grep 'name' buildspec.json | sed -E -e 's/^.+"name":[^"]+"(.+)",?$/\1/g')"
          plugin_display_name="$(grep 'displayName' buildspec.json | sed -E -e 's/^.+"displayName":[^"]+"(.+)",?$/\1/g' || echo "")"

          if [[ "${plugin_display_name}" ]]; then
            echo "pluginName=${plugin_display_name}" >> $GITHUB_OUTPUT
          else
            echo "pluginName=${plugin_name}" >> $GITHUB_OUTPUT
          fi

  macos-build:
    name: Build for macOS 🍏
    runs-on: macos-15
    needs: check-event
    defaults:
      run:
        shell: zsh --no-rcs --errexit --pipefail {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix Permissions 🛠️
        run: chmod -R +x .github/actions/

      - name: Set Up Environment 🔧
        id: setup
        run: |
          local product_name product_version
          read -r product_name product_version <<< "$(jq -r '. | {name, version} | join(" ")' buildspec.json)"
          print "pluginName=${product_name}" >> $GITHUB_OUTPUT
          print "pluginVersion=${product_version}" >> $GITHUB_OUTPUT

      - name: Build Plugin 🧱
        uses: ./.github/actions/build-plugin
        with:
          target: macos-universal
          config: RelWithDebInfo

      - name: Package Plugin 📀
        uses: ./.github/actions/package-plugin
        with:
          target: macos-universal
          config: RelWithDebInfo
          package: true

      - name: Upload macOS Zip Artifact 📡
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-macOS
          path: ${{ github.workspace }}/release/*

  ubuntu-build:
    name: Build for Ubuntu 🐧
    runs-on: ubuntu-24.04
    needs: check-event
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix Permissions 🛠️
        run: chmod -R +x .github/actions/

      - name: Set Up Environment 🔧
        id: setup
        run: |
          read -r product_name product_version <<< "$(jq -r '. | {name, version} | join(" ")' buildspec.json)"
          echo "pluginName=${product_name}" >> $GITHUB_OUTPUT
          echo "pluginVersion=${product_version}" >> $GITHUB_OUTPUT

      - name: Build Plugin 🧱
        uses: ./.github/actions/build-plugin
        with:
          target: x86_64
          config: RelWithDebInfo

      - name: Package Plugin 📀
        uses: ./.github/actions/package-plugin
        with:
          target: x86_64
          config: RelWithDebInfo
          package: true

      - name: Upload Ubuntu Zip Artifact 📡
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-Linux
          path: ${{ github.workspace }}/release/*

  windows-build:
    name: Build for Windows 🪟
    runs-on: windows-2022
    needs: check-event
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Up Environment 🔧
        id: setup
        run: |
          $BuildSpec = Get-Content -Path buildspec.json -Raw | ConvertFrom-Json
          "pluginName=$($BuildSpec.name)" >> $env:GITHUB_OUTPUT
          "pluginVersion=$($BuildSpec.version)" >> $env:GITHUB_OUTPUT

      - name: Build Plugin 🧱
        uses: ./.github/actions/build-plugin
        with:
          target: x64
          config: RelWithDebInfo

      - name: Package Plugin 📀
        uses: ./.github/actions/package-plugin
        with:
          target: x64
          config: RelWithDebInfo
          package: true

      - name: Upload Windows Zip Artifact 📡
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-Windows
          path: ${{ github.workspace }}/release/*
