name: Build Windows ZIP
run-name: Build Windows ZIP - ${{ github.ref_name }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    name: Build OBS Image Reaction for Windows
    uses: ./.github/workflows/build-windows.yaml
    secrets: inherit
